### ISSUE TITLE
"Buffout 4 NG with PDB support (v1.13.1)" - Do you mean 1.31.1?

### ISSUE THREAD

**Issue by SamBWarren** [FWDekker/fo4vr-modlist#12]
I don't see a 1.13.1, so assuming you mean the latest release which is 1.31.1

https://www.nexusmods.com/fallout4/mods/64880?tab=files

**Comment by SamBWarren** [comment]
Additionally, when installing "Classic Ghouls Redux - UFO4P and LotC patch", if you do not have UFO4P already installed and activated, you will not be able to install the UFO4P part of the patch. You might want to instruct users to activate UFO4P, install the Classic Ghouls patch, and then deactivate UFO4P.

This is an absolutely excellent guide, thank you for taking the time to make it.

**Comment by FWDekker** [comment]
Thank you for the corrections! You're correct, I mean 1.31.1; and I will update the patch (since I am the maintainer) to allow manually overriding the pre-selection.

**Comment by SamBWarren** [comment]
Oh, even better! 

BTW, is there a specific reason you suggest FRIK 0.58 over 0.62? As a lefty, I'm inclined to 0.62 for the better support.

**Comment by FWDekker** [comment]
The only reason I don't suggest it is that I haven't personally tested it, and it says "Test". I'll also update the guide to point this out, i.e. say "this is untested" :-)
