### ISSUE TITLE
not all steam depots included in readme

### ISSUE THREAD

**Issue by crazysmile11012** [FWDekker/fo4vr-modlist#22]
In the using dlc section there is only commands for downloading 
- Automatron english
-Automatron 
- Wasteland Workshop01
no commands for installing Far Harbor english, Far Harbor, Nuka-World english, Nuka-World, or the other workshop dlc

**Comment by FWDekker** [comment]
Hiya!

From what I understand, you suggest that I add commands for downloading _all_ non-VR DLC, including those that were not upgraded by the next-gen patch. However, I'm not sure why that would be useful, since the current instructions seem complete and correct to me.

Could you give an example of why this would be useful? Does it reduce the amount you have to download? Or is the current guide incorrect for users with non-English versions of non-VR FO4? Or something else?

**Comment by FWDekker** [comment]
Hiya! Without further information on what your issue means exactly, I won't be able to fix it. Any additional info would be appreciated :-)

**Comment by crazysmile11012** [comment]
Sorry for the late response,, Inclusion of the DLC's  that are not effected by the next gen patch may be of use to some people that are uncomfortable to touch their fo4 flat install's folder, or don't have flat version installed, Your guide is Great! accounting for these edge cases may help some players.

**Comment by crazysmile11012** [comment]
This is a suggestion that I hope won't intrude on your flow and formatting of the guide if implemented, If it does effect the 
no-nonsense nature of the guide feel free to close with a comment, Thanks for your time friend.

**Comment by FWDekker** [comment]
Ah, now I understand. That's a fair reason. I'll have to think about how to put that in the guide without breaking the flow, as you say, but I don't have time for that right now.

As a note to myself, here's the list of depots for all DLC:
```
NW:
download_depot 377160 490650
download_depot 377160 393895

VTW:
download_depot 377160 480631
download_depot 377160 393885

C:
download_depot 377160 480630

FH:
download_depot 377160 435881
download_depot 377160 435882

WW:
download_depot 377160 435880

AU:
download_depot 377160 435870
download_depot 377160 435871
```
(There's some overlap with the next-gen update, which is not downgraded with the instructions above.)

**Comment by FWDekker** [comment]
Done! Let me know if you have any feedback on how I added the instructions to Section 2.3!
