### ISSUE TITLE
Some settings holotapes do not appear in Inventory

### ISSUE THREAD

**Issue by VovaLeder** [FWDekker/fo4vr-modlist#7]
Tried different approaches, but after leaving the vault I miss holotapes for "Survival Options" and "Better VATS" (even when I "pick up" them after mirror cast scene.

I always has to disable UFO4P for leaving the vault. I tried to use "SKK Fast Start new game", got the message for acquiring item of "Better VATS" but then did not have anything in Misc at all when I looked in pip-boy. 

:(

**Comment by FWDekker** [comment]
Uh oh. I haven't had that issue, so not sure what's going wrong. Your inventory is deleted when you exit the cryopod, so the holotapes are probably being added too soon.

As a workaround for now, you can try starting a new game without those two mods, then playing the intro (or skipping with SKK Fast Start), then exiting the game (creating an exit save (which can be loaded only once)), then enabling the mods, and then you should get the holotapes after the intro.

That said, I didn't experience missing holotapes, so I'll have to do some more testing to see if I can pinpoint the exact cause.

**Comment by VovaLeder** [comment]
Thanks! Workaround helped to acquire needed holotapes.

Also I noticed, that with SKK I do not have _any_ holotapes at the start (so I didn't have for See Through Scopes (even though it is not needed))

**Comment by FWDekker** [comment]
I was trying out all kinds of workarounds, none of which I was satisfied with, when I realised you can just craft both of those holotapes using a chemistry station...  There's one in Sanctuary Hills, so I'll add that to the guide.

**Comment by FWDekker** [comment]
Done :-)

I've also fixed the guide to say that UFO4P should be disabled during the intro.

btw, UFO4P is quite a complex mod which changes a lot of things in a lot of places, so it's heavily discouraged to disable the mod during a playthrough, even temporarily. If you disabled it during the intro to get the elevator working, this _may_ cause issues in the long term, though I cannot predict how, why, or in what scale.

For stability, the best option would be to start an entirely new game, with UFO4P disabled throughout the entire intro, though whether that's worth the effort is up to you. Sorry for the inconvenience :/
